### ISSUE TITLE
[Web]: User needs to scroll down in order to see message marked as correct answer.

### ISSUE THREAD

**Issue by goodideagiver** [AnswerOverflow/AnswerOverflow#258]
### aspect

Message Result Page

### Suggestion?

In order to see an answer for the question (message marked as answer) user needs to scroll down.

![image](https://user-images.githubusercontent.com/55458485/224635770-6533d10c-9c4c-4f1b-a708-614e30f19d17.png)

### Possible Solutions

Duplicate message marked as answer right below the question.

![image](https://user-images.githubusercontent.com/55458485/224636060-f5d65fdf-1694-4eda-b408-1b0472b328d5.png)

### Extra Information

If this idea is approved I can try to implement it.

**Comment by RhysSullivan** [comment]
Thanks for the suggestion! I totally agree - there could be some UX improvements on the message result page and this is one of them

We're going through a bit of a transition phase on the codebase this week while we move over to the open source version, so while you're welcome to implement this feature it'd be a bit of an awkward time to do it 😅. This is because we're doing a lot of the styles of the site and the message page is getting redone 

If you want to contribute though feel free to join the discord and we can coordinate! Thanks!

**Comment by RhysSullivan** [comment]
with how simple this one is we should get it added soon, this one has been sitting for a bit too long

tracking at: https://answeroverflow.notion.site/Jump-to-solution-button-a8c9429b7c3e4f2999a4d9db9162a3ea?pvs=4
