### ISSUE TITLE
Sync User Delete

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#59]
### What is this for?

bot

### Feature

As a user, when I delete my Discord account I expect my messages to deleted from Answer Ovreflow

### Ideal solution or implementation

Listen to the on guild user delete event and then fetch that user to see if it throws a not found exception, if so then this user has been deleted (possibly fetch after a delay?)

### Alternative solutions or implementations

Hope Discord implements an 'on user delete' event

**Comment by KrishAgarwal2811** [comment]
I think this topic can be ignored as you can face only two cases after a person deletes their discord account:
1. The user has already given their consent - no worries, you can still show them because you still have their consent
2. The user has not given their consent - you can show their messages as you do now to show messages from people who haven't given their consent because discord itself doesn't delete the messages from deleted users

Also, for the second point, you cannot track if a person has deleted their account.

**Comment by RhysSullivan** [comment]
There is the issue of storing their username and avatar post delete.

If we were to store the messages of deleted users, I'd at least like to swap it out to "Deleted User" which still requires to detected a deleted user

Once it gets to a larger scale, I'll reach out to Discord about how to best handle this issue

For detecting if an account is deleted, I'm guessing combining the "onGuildMemberLeave" event with a fetch of that user ID and seeing if it returns 404 would work as a detection method

**Comment by RhysSullivan** [comment]
> Why do you store the avatar and username? When you can just fetch those details with the userID and cache them for better speeds.

Because at the scale that answer overflow is going to go at caching that data would cause an issue and introduce a lot of complications 

Discord rate limits are pretty aggressive

**Comment by KrishAgarwal2811** [comment]
How would you track changes in their username/avatars?
